name: MavenTestCI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  mavenTest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout files from github
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Dependies
        run: mvn compile

      - name: Build App
        run: mvn package -DskipTests

      - name: Ren test
        run: mvn test

